# Site settings
title: ELIXIR Ireland
description: >-
  ELIXIR Ireland is the Irish node of the international
  organisation ELIXIR, centred in Europe, which promotes the
  sharing of resources and expertise in computational biology.
baseurl: ""
url: "https://elixir-ireland.ie"
twitter_username: elixir-ireland
github_username: codemeleon
logo: "/assets/images/ELIXIR-IE_logo.png"

# Build settings
plugins:
  - jekyll-feed

include:
  - css
  - images
  - js

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - "*.bak"
  - README.md
  - Dockerfile
  - docker-compose.yml
